// Generated by Templates/Version.swift.stencil

public extension Archery {
    public static var version: String {
        return "0.1.1"
    }

    public static var apiLevel: String {
        return "1"
    }
}
