// Generated by Templates/Version.swift.stencil

public extension Archery {
    static var version: String {
        return "0.2.0"
    }

    static var apiLevel: String {
        return "2"
    }
}
