#if !canImport(ObjectiveC)
    import XCTest

    extension ArcherfileParsingTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__ArcherfileParsingTests = [
            ("testArcherfileParsingFailsFromScriptsArray", testArcherfileParsingFailsFromScriptsArray),
            ("testArcherfileParsingFromEmptyScripts", testArcherfileParsingFromEmptyScripts),
            ("testArcherfileParsingFromMinimalFile", testArcherfileParsingFromMinimalFile),
            ("testArcherfileParsingFromSomeLoadersAndBashShorthand", testArcherfileParsingFromSomeLoadersAndBashShorthand),
            ("testArcherfileParsingFromSomeLoadersAndShorthand", testArcherfileParsingFromSomeLoadersAndShorthand),
            ("testArcherfileParsingFromSomeScripts", testArcherfileParsingFromSomeScripts),
            ("testArcherfileParsingFromSomeScriptsAndShorthand", testArcherfileParsingFromSomeScriptsAndShorthand),
        ]
    }

    extension ArcheryKitTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__ArcheryKitTests = [
            ("testExample", testExample),
        ]
    }

    extension MetadataTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__MetadataTests = [
            ("testCanBasicallyBeDecoded", testCanBasicallyBeDecoded),
            ("testCanBasicallyBeEncoded", testCanBasicallyBeEncoded),
            ("testDecodeFromStringAsYaml", testDecodeFromStringAsYaml),
            ("testDecodingComplexExample", testDecodingComplexExample),
        ]
    }

    extension ScriptParsingTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__ScriptParsingTests = [
            ("testScriptParsingFailsFromMinimalArrowWithComplexRepo", testScriptParsingFailsFromMinimalArrowWithComplexRepo),
            ("testScriptParsingFromFullScript", testScriptParsingFromFullScript),
            ("testScriptParsingFromFullScriptIncludingMetadata", testScriptParsingFromFullScriptIncludingMetadata),
            ("testScriptParsingFromListOfBashArrow", testScriptParsingFromListOfBashArrow),
            ("testScriptParsingFromMinimalArrow", testScriptParsingFromMinimalArrow),
        ]
    }

    public func __allTests() -> [XCTestCaseEntry] {
        return [
            testCase(ArcherfileParsingTests.__allTests__ArcherfileParsingTests),
            testCase(ArcheryKitTests.__allTests__ArcheryKitTests),
            testCase(MetadataTests.__allTests__MetadataTests),
            testCase(ScriptParsingTests.__allTests__ScriptParsingTests),
        ]
    }
#endif
