#if !canImport(ObjectiveC)
    import XCTest

    extension ArcheryInterfaceTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__ArcheryInterfaceTests = [
            ("testExample", testExample),
        ]
    }

    public func __allTests() -> [XCTestCaseEntry] {
        return [
            testCase(ArcheryInterfaceTests.__allTests__ArcheryInterfaceTests),
        ]
    }
#endif
